spring:
  application:
    name: ms-order

  datasource:
    url: jdbc:postgresql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:5432}/${DB_NAME:order_db}
    username: ${DB_CONNECTION_USERNAME:postgres}
    password: ${DB_CONNECTION_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate

  config:
    import: configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081

resilience4j:
  circuitbreaker:
    instances:
      getOrderById: # http://localhost:8081/actuator/circuitbreakers
        # configs for close state
        sliding-window-type: count_based
        failure-rate-threshold: 50.0
        sliding-window-size: 10
        # configs for open state
        wait-duration-in-open-state: 10s
        # configs for half-open state
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 2
        max-wait-duration-in-half-open-state: 15000
