spring:
  application:
    name: ms-payment

  datasource:
    url: jdbc:postgresql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:5432}/${DB_NAME:payment_db}
    username: ${DB_CONNECTION_USERNAME:postgres}
    password: ${DB_CONNECTION_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate

  config:
    import: configserver:http://localhost:8888

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8082
